# -*- coding: utf-8 -*-
"""obtener_seleccion.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wb4PKMXGWjOrGe-5BBMN5E1Ld4D7Nhs3
"""

import tkinter as tk
from tkinter import messagebox

def obtener_seleccion():
    seleccion = seleccion_var.get()
    messagebox.showinfo("Selección", f"Opción seleccionada: {seleccion}")

def reiniciar_seleccion():
    seleccion_var.set(None)

# Crear ventana
ventana = tk.Tk()

# Variable para almacenar la selección
seleccion_var = tk.StringVar()

# Crear RadioButton
opcion1 = tk.Radiobutton(ventana, text="Opción 1", variable=seleccion_var, value="Opción 1")
opcion2 = tk.Radiobutton(ventana, text="Opción 2", variable=seleccion_var, value="Opción 2")
opcion3 = tk.Radiobutton(ventana, text="Opción 3", variable=seleccion_var, value="Opción 3")

# Botón de obtención de selección
boton_obtener = tk.Button(ventana, text="Obtener selección", command=obtener_seleccion)

# Botón de reinicio
boton_reiniciar = tk.Button(ventana, text="Reiniciar", command=reiniciar_seleccion)

# Mostrar RadioButton y botones
opcion1.pack()
opcion2.pack()
opcion3.pack()
boton_obtener.pack()
boton_reiniciar.pack()

# Ejecutar ventana
ventana.mainloop()