# -*- coding: utf-8 -*-
"""conexionsql.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wb4PKMXGWjOrGe-5BBMN5E1Ld4D7Nhs3
"""

import sqlite3

# Conexión a la base de datos
conexion = sqlite3.connect('alumnos.db')

# Crear tabla Alumnos
cursor = conexion.cursor()
cursor.execute('''CREATE TABLE Alumnos
                  (id INTEGER, nombre TEXT, apellido TEXT)''')

# Insertar datos en la tabla
alumnos = [(1, 'Juan', 'Pérez'),
           (2, 'María', 'López'),
           (3, 'Pedro', 'González'),
           (4, 'Laura', 'García'),
           (5, 'Carlos', 'Martínez'),
           (6, 'Ana', 'Sánchez'),
           (7, 'David', 'Rodríguez'),
           (8, 'Sofía', 'Fernández')]

cursor.executemany('INSERT INTO Alumnos VALUES (?, ?, ?)', alumnos)

# Guardar cambios y cerrar conexión
conexion.commit()
conexion.close()

# Búsqueda de un alumno por nombre
nombre_buscar = 'María'

# Conexión a la base de datos nuevamente
conexion = sqlite3.connect('alumnos.db')

# Realizar la búsqueda
cursor = conexion.cursor()
cursor.execute('SELECT * FROM Alumnos WHERE nombre = ?', (nombre_buscar,))
alumno_encontrado = cursor.fetchone()

# Mostrar los datos por consola
if alumno_encontrado:
    print(f'ID: {alumno_encontrado[0]}')
    print(f'Nombre: {alumno_encontrado[1]}')
    print(f'Apellido: {alumno_encontrado[2]}')
else:
    print('No se encontró ningún alumno con ese nombre')

# Cerrar conexión
conexion.close()