# -*- coding: utf-8 -*-
"""peliculas/models.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wb4PKMXGWjOrGe-5BBMN5E1Ld4D7Nhs3
"""

from django.conf import settings
from django.db import models
from django.shortcuts import render, get_object_or_404
from django.urls import path
from django.contrib import admin

# Configuración del proyecto
settings.configure(
    DEBUG=True,
    SECRET_KEY='your-secret-key',
    ROOT_URLCONF=__name__,
    DATABASES={
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': 'db.sqlite3',
        }
    },
    INSTALLED_APPS=[
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'peliculas',
    ],
    TEMPLATES=[
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
            },
        },
    ],
)

# Definición de modelos
class Director(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Pelicula(models.Model):
    titulo = models.CharField(max_length=100)
    descripcion = models.TextField()
    director = models.ForeignKey(Director, on_delete=models.CASCADE)

    def __str__(self):
        return self.titulo

# Vistas
def director_detail(request, director_id):
    director = get_object_or_404(Director, pk=director_id)
    peliculas = Pelicula.objects.filter(director=director)
    return render(request, 'peliculas/director_detail.html', {'director': director, 'peliculas': peliculas})

def pelicula_detail(request, pelicula_id):
    pelicula = get_object_or_404(Pelicula, pk=pelicula_id)
    return render(request, 'peliculas/pelicula_detail.html', {'pelicula': pelicula})

# Configuración de URLs
urlpatterns = [
    path('admin/', admin.site.urls),
    path('directores/<int:director_id>/', director_detail, name='director_detail'),
    path('peliculas/<int:pelicula_id>/', pelicula_detail, name='pelicula_detail'),
]

# Ejecución del servidor de desarrollo de Django
if __name__ == '__main__':
    from django.core.management import execute_from_command_line
    execute_from_command_line(['cineapp.py', 'runserver'])