# -*- coding: utf-8 -*-
"""obtenerimpares.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wb4PKMXGWjOrGe-5BBMN5E1Ld4D7Nhs3
"""

from functools import reduce

def obtener_impares(lista):
    impares = filter(lambda x: x % 2 != 0, lista)
    return reduce(lambda x, y: x + y, impares)

# Ejemplo de uso
numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
suma_impares = obtener_impares(numeros)

print("Lista original:", numeros)
print("Suma de los elementos impares:", suma_impares)