# -*- coding: utf-8 -*-
"""mitxt.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wb4PKMXGWjOrGe-5BBMN5E1Ld4D7Nhs3
"""

# Crear el archivo de texto
nombre_archivo = "mi_archivo.txt"

with open(nombre_archivo, "w") as archivo:
    archivo.write("Primera línea\n")

# Abrir y escribir en el archivo nuevamente
with open(nombre_archivo, "a") as archivo:
    archivo.write("Segunda línea\n")