# -*- coding: utf-8 -*-
"""bisiesto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wb4PKMXGWjOrGe-5BBMN5E1Ld4D7Nhs3
"""

def es_bisiesto(año):
    if año % 4 == 0:
        if año % 100 == 0:
            if año % 400 == 0:
                return True  # Año divisible por 400 (es bisiesto)
            else:
                return False  # Año divisible por 100 pero no por 400 (no es bisiesto)
        else:
            return True  # Año divisible por 4 pero no por 100 (es bisiesto)
    else:
        return False  # Año no divisible por 4 (no es bisiesto)

# Ejemplo de uso
año = 2024
if es_bisiesto(año):
    print(año, "es un año bisiesto")
else:
    print(año, "no es un año bisiesto")