# -*- coding: utf-8 -*-
"""numeroinverso.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wb4PKMXGWjOrGe-5BBMN5E1Ld4D7Nhs3
"""

# Mostrar los números del 100 al 1 en orden inverso
for num in range(100, 0, -1):
    print(num)