# -*- coding: utf-8 -*-
"""IMC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wb4PKMXGWjOrGe-5BBMN5E1Ld4D7Nhs3
"""

# Pedir al usuario el peso y la estatura
peso = float(input("Ingresa tu peso en kg: "))
estatura = float(input("Ingresa tu estatura en metros: "))

# Calcular el índice de masa corporal (IMC)
imc = peso / (estatura ** 2)

# Redondear el IMC a dos decimales
imc = round(imc, 2)

# Imprimir el resultado
print("Tu índice de masa corporal es", imc)